#!/bin/sh

system_type=$(uname -s)

echo "[YADM] Running bootstrap from $0"

if ! which brew > /dev/null; then
  echo "[YADM] Homebrew is not insalled, exiting..."
  exit 1
fi

echo "[YADM] Updating homebrew bundle"
brew bundle --global

if [ -d "$HOME/.iterm2" ]; then
  echo "[YADM] iTerm setup"
  defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
fi

if [ ! -d ~/.tmux/plugins/tpm ]; then
  echo "[YADM] Tmux setup"
  git clone --depth 1 https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

if which n >/dev/null; then
  echo "[YADM] Node setup (https://github.com/tj/n)"
  n lts
fi

if which nvim > /dev/null; then
  echo "[YADM] NeoVim setup"
  nvim '+PlugUpdate' '+PlugClean' '+qa'
fi

echo "[YADM] done."
