#!/bin/sh

system_type=$(uname -s)

echo "Updating homebrew bundle"
brew bundle --global

if [ -d "$HOME/.iterm2" ]; then
  echo "Setting iTerm preference folder"
  defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
fi

if command -v n >/dev/null 2>&1; then
  echo "Installing node with n (https://github.com/tj/n)"
  n lts
fi

if command -v nvim >/dev/null 2>&1; then
  echo "Bootstraping NeoVim"
  nvim '+PlugUpdate' '+PlugClean!' '+qall'
fi
