-- general config that is used in several places
-- local table = {
-- 	kind = {
-- 		Array = "",
-- 		Boolean = "",
-- 		Class = "",
-- 		Color = "",
-- 		Constant = "",
-- 		Constructor = "",
-- 		Enum = "",
-- 		EnumMember = "",
-- 		Event = "",
-- 		Field = "",
-- 		File = "",
-- 		Folder = "󰉋",
-- 		Function = "",
-- 		Interface = "",
-- 		Key = "",
-- 		Keyword = "",
-- 		Method = "",
-- 		Module = "",
-- 		Namespace = "",
-- 		Null = "󰟢",
-- 		Number = "",
-- 		Object = "",
-- 		Operator = "",
-- 		Package = "",
-- 		Property = "",
-- 		Reference = "",
-- 		Snippet = "",
-- 		String = "",
-- 		Struct = "",
-- 		Text = "",
-- 		TypeParameter = "",
-- 		Unit = "",
-- 		Value = "",
-- 		Variable = "",
-- 	},
-- 	git = {
-- 		LineAdded = "",
-- 		LineModified = "",
-- 		LineRemoved = "",
-- 		FileDeleted = "",
-- 		FileIgnored = "◌",
-- 		FileRenamed = "",
-- 		FileStaged = "S",
-- 		FileUnmerged = "",
-- 		FileUnstaged = "",
-- 		FileUntracked = "U",
-- 		Diff = "",
-- 		Repo = "",
-- 		Octoface = "",
-- 		Branch = "",
-- 	},
-- 	ui = {
-- 		ArrowCircleDown = "",
-- 		ArrowCircleLeft = "",
-- 		ArrowCircleRight = "",
-- 		ArrowCircleUp = "",
-- 		BoldArrowDown = "",
-- 		BoldArrowLeft = "",
-- 		BoldArrowRight = "",
-- 		BoldArrowUp = "",
-- 		BoldClose = "",
-- 		BoldDividerLeft = "",
-- 		BoldDividerRight = "",
-- 		BoldLineLeft = "▎",
-- 		BookMark = "",
-- 		BoxChecked = "",
-- 		Bug = "",
-- 		Stacks = "",
-- 		Scopes = "",
-- 		Watches = "󰂥",
-- 		DebugConsole = "",
-- 		Calendar = "",
-- Check = "",
-- 		ChevronRight = "",
-- 		ChevronShortDown = "",
-- 		ChevronShortLeft = "",
-- 		ChevronShortRight = "",
-- 		ChevronShortUp = "",
-- 		Circle = "",
-- 		Close = "󰅖",
-- 		CloudDownload = "",
-- 		Code = "",
-- 		Comment = "",
-- 		Dashboard = "",
-- 		DividerLeft = "",
-- 		DividerRight = "",
-- 		DoubleChevronRight = "»",
-- 		Ellipsis = "",
-- 		EmptyFolder = "",
-- 		EmptyFolderOpen = "",
-- 		File = "",
-- 		FileSymlink = "",
-- 		Files = "",
-- 		FindFile = "󰈞",
-- 		FindText = "󰊄",
-- 		Fire = "",
-- 		Folder = "󰉋",
-- 		FolderOpen = "",
-- 		FolderSymlink = "",
-- 		Forward = "",
-- 		Gear = "",
-- 		History = "",
-- 		Lightbulb = "",
-- 		LineLeft = "▏",
-- 		LineMiddle = "│",
-- 		List = "",
-- 		Lock = "",
-- 		NewFile = "",
-- 		Note = "",
-- 		Package = "",
-- 		Pencil = "󰏫",
-- 		Plus = "",
-- 		Project = "",
-- 		Search = "",
-- 		SignIn = "",
-- 		SignOut = "",
-- 		Tab = "󰌒",
-- 		Table = "",
-- 		Target = "󰀘",
-- 		Telescope = "",
-- 		Text = "",
-- 		Tree = "",
-- 		Triangle = "󰐊",
-- 		TriangleShortArrowDown = "",
-- 		TriangleShortArrowLeft = "",
-- 		TriangleShortArrowRight = "",
-- 		TriangleShortArrowUp = "",
-- 	},
-- 	diagnostics = {
-- 		BoldError = "",
-- 		Error = "",
-- 		BoldWarning = "",
-- 		Warning = "",
-- 		BoldInformation = "",
-- 		Information = "",
-- 		BoldQuestion = "",
-- 		Question = "",
-- 		BoldHint = "",
-- 		Hint = "󰌶",
-- 		Debug = "",
-- 		Trace = "✎",
-- 	},
-- 	misc = {
-- 		Robot = "󰚩",
-- 		Squirrel = "",
-- 		Tag = "",
-- 		Watch = "",
-- 		Smiley = "",
-- 		Package = "",
-- 		CircuitBoard = "",
-- 	},
-- }

return {
	borders = {
		telescope = { "▔", "▕", "▁", "▏", "🭽", "🭾", "🭿", "🭼" },
		telescope_thick = { "▀", "▐", "▄", "▌", "▛", "▜", "▟", "▙" },
	},

	icons = {
		ui = {
			BoxChecked = "",
			Branch = "",
			Check = "󰄳",
			Circle = "",
			CircleOutlined = "○",
			-- CircleOutlined = " ",
			Close = "󰅖",
			Code = "",
			Diff = "",
			Fire = "",
			Folder = "󰉋",
			-- Folder = "",
			Forward = "",
			Ghost = "󰚌",
			Information = "",
			Line = "│",
			LineDouble = "║",
			LineLeft = "▏",
			NewFile = "",
			Package = "",
			Quit = "",
			Search = "",
		},
		git = {
			-- Added = "", -- Added = "",
			-- Modified = "", -- Modified = "",
			-- Removed = "", -- Removed = "󰅖",
			Added = "+", -- Added = "",
			Modified = "!", -- Modified = "",
			Removed = "-", -- Removed = "󰅖",
		},
		diagnostics = {
			Info = "", -- Info = "",
			-- Warn = "", -- Warn = "",
			Warn = "",
			Error = "", -- Error = "",
			Hint = "󱤅", -- Hint = "󰌶",  "⚑",
			Other = "󰠠",
		},
	},
}
