return {
	ui = {
		BoxChecked = "",
		Branch = "",
		Check = "󰄳",
		Circle = "",
		CircleOutlined = "○",
		-- CircleOutlined = " ",
		Close = "󰅖",
		Code = "",
		Diff = "",
		Fire = "",
		Folder = "󰉋",
		-- Folder = "",
		Forward = "",
		Ghost = "󰚌",
		Information = "",
		Line = "│",
		LineDouble = "║",
		LineLeft = "▏",
		NewFile = "",
		Package = "",
		Quit = "",
		Search = "",
		Tree = "",
	},
	git = {
		Added = "+", -- Added = "", -- Added = "",
		Modified = "!", -- Modified = "", -- Modified = "",
		Removed = "-", -- Removed = "", -- Removed = "󰅖",
	},
	diagnostics = {
		Info = "●", --"", -- Info = "",
		Warn = "●", --"", -- Warn = "", -- Warn = "",
		Error = "●", --"", -- Error = "",
		Hint = "●", -- "󱤅", -- Hint = "󰌶",  "⚑",
		Other = "●", --"󰠠",
	},
}
