return {
	ui = {
		BoxChecked = "",
		Branch = "",
		Check = "󰄳",
		Circle = "",
		CircleOutlined = "○",
		-- CircleOutlined = " ",
		Close = "󰅖",
		Code = "",
		Diff = "󰦓",
		Fire = "",
		Folder = "󰉋",
		-- Folder = "",
		Forward = "",
		Ghost = "󰚌",
		Git = "󰊢",
		Hint = "󰌶",
		Information = "",
		Line = "│",
		LineDouble = "║",
		LineLeft = "▏",
		NewFile = "",
		Package = "",
		Quit = "",
		Search = "",
		Tree = "",
	},
	git = {
		-- Added = "+", -- Added = "", -- Added = "",
		-- Modified = "!", -- Modified = "", -- Modified = "",
		-- Removed = "-", -- Removed = "", -- Removed = "󰅖",
		Added = " ",
		Modified = " ",
		Removed = " ",
	},
	diagnostics = {
		Info = "●", -- ●   ,
		Warn = "●", -- ●   ,
		Error = "●", -- ●   
		Hint = "⚑", -- ● 󱤅 󰌶 ⚑
		Other = "●", --"󰠠",
	},
}
